### ISSUE TITLE
vignettes not working

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pfmc-assessments/nwfscDeltaGLM#11] opened 2021-05-15 12:41 UTC
@ericward-noaa 
FYI I tried to run the models in both vignettes and I am getting the following and I know jags works because I ran a different model based on a random example from googling and it gave me parameter estimates. I am guessing it has something to do with me using a newer version of R?
```
Error in checkForRemoteErrors(lapply(cl, recvResult)) : 
  3 nodes produced errors; first error: RUNTIME ERROR:
Unable to resolve the following parameters:
strata[1] (line 98)
strata[2] (line 98)
strata[3] (line 90, 98)
strata[4] (line 98)
strata[5] (line 90, 98)
strata[6] (line 98)
strata[7] (line 98)
strata[8] (line 98)
strata[9] (line 90, 98)
strata[10] (line 90, 98)
strata[11] (line 98)
strata[12] (line 98)
strata[13] (line 98)
strata[14] (line 90, 98)
strata[15] (line 90, 98)
strata[16] (line 90, 98)
strata[17] (line 98)
strata[18] (line 98)
strata[19] (line 90, 98)
strata[20] (line 98)
strata[21] (line 90, 98)
strata[22] (line 90, 98)
strata[23] (line 90, 98)
strata[24] (line 98)
strata[25] (line 90, 98)
strata[26] (line 98)
strata[27] (line 90, 98)
strata[28] (line 90, 98)
strata[29] (line 98)
strata[30] (line 98)
strata[31] (line 90, 98)
strata[32] (line 98)
strata[33] (line 90, 98)
strata[34] (line 90, 98)
strata[35] (line 90, 98)
strata[36] (line 90, 98)
strata[37] (line 98)
strata[38] (line 98)
strata[39] (line 90, 98)
stra
```

Using the following
```
> sessionInfo()
R Under development (unstable) (2021-01-17 r79842)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] nwfscDeltaGLM_1.0 devtools_2.4.0    usethis_2.0.1     R2jags_0.6-1     
[5] rjags_4-10        coda_0.19-4      

loaded via a namespace (and not attached):
 [1] magrittr_2.0.1    pkgload_1.2.1     lattice_0.20-41   R6_2.5.0         
 [5] rlang_0.4.11      fastmap_1.1.0     tools_4.1.0       pkgbuild_1.2.0   
 [9] parallel_4.1.0    grid_4.1.0        sessioninfo_1.1.1 cli_2.5.0        
[13] withr_2.4.2       remotes_2.3.0     ellipsis_0.3.2    R2WinBUGS_2.1-21 
[17] rprojroot_2.0.2   abind_1.4-5       lifecycle_1.0.0   crayon_1.4.1     
[21] processx_3.5.2    purrr_0.3.4       callr_3.7.0       fs_1.5.0         
[25] ps_1.6.0          testthat_3.0.2    memoise_2.0.0     glue_1.4.2       
[29] cachem_1.0.4      compiler_4.1.0    desc_1.3.0        prettyunits_1.1.1
[33] boot_1.3-25      
> 
```

**Comment by ericward-noaa** [comment] 2021-05-15 20:39
@kellijohnson-NOAA Thanks for testing this. I still get it to run (I'm starting with example.Rmd) and I think I know what the issue is. There's a file called 'onLoad.r' that may or may not have been added to .gitignore, so it may not show up locally for you. If not, create it and make sure the first line is like this:

https://github.com/nwfsc-assess/nwfscDeltaGLM/blob/c6be7e2ec599d60ef865071c78d17f63bcb5d7de/R/onLoad.R#L2

I had deleted this file a while back because it seemed like bad style. And I just commented out this line, rebuilt the package locally, and reproduced the same errors you're getting. The issue is that when the lines are commented out, the strata, vessel, and interactions are passed into JAGS as strings -- and this 'onLoad.r' keeps them as factors

**Comment by kellijohnson-NOAA** [comment] 2021-05-16 22:45
It wasn't ignored, so I can see the file and it has 
```
.onLoad <- function(libname, pkgname) {
  options(stringsAsFactors = TRUE)
  # assign to this environment to keep from overwriting user's workspace
  # assign("Letters", Letters, envir=.GlobalEnv)
}
```
but when I `load_all()` I am [getting this error because](https://developer.r-project.org/Blog/public/2020/02/16/stringsasfactors/)
![image](https://user-images.githubusercontent.com/4108564/118415114-50475d00-b65d-11eb-8f1d-2102a02853c7.png)

**Comment by ericward-noaa** [comment] 2021-05-16 23:04
Can you confirm you can't knit the example.Rmd file as is? I also swapped out the 1st code chunk with `devtools::load_all()`, and that also works fine for me. The sessionInfo() for me is: 

R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3

**Comment by kellijohnson-NOAA** [comment] 2021-05-16 23:19
Correct, it doesn't work for me running the code line by line from the .R file our rmarkdown::render("vignettes/example.Rmd") regardless if I am installing from github or loading all.

**Comment by ericward-noaa** [comment] 2021-05-16 23:23
What about when you get to line ~ 72 of example.Rmd -- what does 

DataList$Data look like? Are 'year', 'strata', 'vessel', 'strataYear', and 'vesselYear' all factors?

**Comment by kellijohnson-NOAA** [comment] 2021-05-16 23:24
No ...
![image](https://user-images.githubusercontent.com/4108564/118416167-36a91400-b663-11eb-951f-23740e2a750b.png)

**Comment by ericward-noaa** [comment] 2021-05-16 23:35
I think this is probably the issue then -- vessel and strata specifically. It's weird that on a Mac, they're returned as factors -- but not PC. Anyway, I pushed this change to coerce them to factors:
https://github.com/nwfsc-assess/nwfscDeltaGLM/blob/9f9de5aeeeb33c7558ff36f2174b66bbf5a0140c/R/processData.r#L113

**Comment by kellijohnson-NOAA** [comment] 2021-05-16 23:40
Now I can fit the model, but I get an error with doMCMCDiags()
```
> doMCMCDiags(datalist=DataList, 
+             mods=fitted_models,
+             strata.limits=strata.limits)
Error in IndicesByStrata[, StratI, ModelNumber, 1] <- McmcIndices$byYearAndStrata$IndexMean[Which] : 
  replacement has length zero
```

**Comment by ericward-noaa** [comment] 2021-05-16 23:49
Alright -- try again. I think it was the same issue with strata not being a factor, here:

https://github.com/nwfsc-assess/nwfscDeltaGLM/blob/4b5854aa47b0aa87be4ba9bd635276619a2e51b9/R/doMCMCDiags.r#L162

**Comment by kellijohnson-NOAA** [comment] 2021-05-16 23:54
Bingo ... looks like we are good to go. Thanks for doing all the debugging.

**Comment by ericward-noaa** [comment] 2021-05-16 23:54
Great -- ok, I'll close this out

**Closed as completed by ericward-noaa** 2021-05-16 23:54 UTC
